BE-SwimMeet model, serializer and view
MarisiaS/SMM pull request #53
Opened 2024-02-21 06:59 UTC by MarisiaS

This PR addresses issue #27  

**Implementation**

1. **backend/api/models.py**
Implemented the SwimMeet model with the following fields:

- name: required
- date: required
- time: Can be null
- site: This is a foreignKey to Site. Set on_delete to cascate because without a site configurate a swim meet is not posible (num lanes is needed to generate the heats)

2. **backend/api/migrations/0011_swimmeet.py**
After creating the model, I ran the `makemigrations` command and the migration for the SwimMeet model was created.

3.  **backend/api/serializers/SwimMeetSerializer.py**
Created a Model serializer for the SwimMeet model. Included all the fields plus the site name.

4. **backend/api/views/EventTypeView.py**
Created a basic Model View  set for SwimMeet.
The data is order by date. 
Search by name is allow

5. **backend/api/urls.py**
Added a router to generate the endpoints for SwimMeet.

**Swagger**

The endpoints are accessible through Swagger.

I tried each of the new endpoints successfully. I was able to create, delete, patch and get an swim meet.
When posting and patching, I got the expected error for entering invalid data.

2024-02-22 18:51 UTC, viriponce requested changes
The endpoints are working as expected, I was able to post, patch, delete and get swim meets.

Just a couple of observations:
Issue #27 calls for fixtures, those are not included in this PR.
I see you added search and sort functionality, should we add then the insensitive collation in the model?

2024-02-22 18:51 UTC, viriponce commented on backend/api/models.py
> +    date = models.DateField(null=True, blank=True)
The user story and the description indicate that this field is required therefore null and blank attributes should be false.

2024-02-22 18:51 UTC, viriponce commented on backend/api/views/SwimMeetView.py
> +@extend_schema(tags=['SwimMeet'])
is a space missing between words?

2024-02-23 05:56 UTC, MarisiaS commented
> Just a couple of observations: Issue #27 calls for fixtures, those are not included in this PR. I see you added search and sort functionality, should we add then the insensitive collation in the model?

I just added sorting by date, so the insensitive collation is not needed.

2024-02-23 06:46 UTC, viriponce approved these changes
LGTM
Thank you Marisia!

2024-02-23 06:47 UTC, viriponce commented
> > Just a couple of observations: Issue #27 calls for fixtures, those are not included in this PR. I see you added search and sort functionality, should we add then the insensitive collation in the model?
> 
> I just added sorting by date, so the insensitive collation is not needed.

Sorry, I got confuse with name but name is a search filter. :)

2024-02-23 06:59 UTC, merged